// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Una tabla leída de un CSV.
 */
export type Csv = { 
/**
 * Con qué se separan las columnas.
 */
separator: string, 
/**
 * Cómo estaba escrito.
 */
encoding: Encoding, 
/**
 * Los nombres de las columnas, de la primera fila.
 */
headers: Array<string>, 
/**
 * Las filas de datos, cada una con un valor por columna.
 */
rows: Array<Array<string>>, };

/**
 * Cómo estaba escrito el archivo.
 */
export type Encoding = "utf8" | "latin1";

/**
 * Qué columna le toca a cada variable.
 */
export type Mapping = { 
/**
 * Por variable, la columna que la rellena, o `null` si ninguna.
 */
columns: { [key in string]: number | null }, };

/**
 * Una fila del CSV con lo que valdría cada variable.
 */
export type Row = { 
/**
 * Qué fila del archivo es, contando desde 1 sin la cabecera.
 */
number: number, 
/**
 * Lo que vale cada variable en esta fila.
 */
values: { [key in string]: string }, 
/**
 * Lo que le falta o no vale, si algo.
 */
problems: Array<RowProblem>, };

/**
 * Lo que le pasa a una fila del CSV.
 */
export type RowProblem = { 
/**
 * La variable de la que se habla.
 */
variable: string, 
/**
 * Qué le pasa, listo para enseñar.
 */
message: string, };
