// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Un error de sintaxis del código de un bloque.
 */
export type CodeError = { 
/**
 * Lo que dice Typst.
 */
message: string, 
/**
 * En qué línea del código del bloque, contando desde 1.
 */
line: number, 
/**
 * En qué columna, contando desde 1 y en caracteres.
 */
column: number, 
/**
 * Sugerencias de Typst para arreglarlo, si las hay.
 */
hints: Array<string>, };
