// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dónde está el código de un elemento dentro del código generado.
 */
export type CodeSpan = { 
/**
 * El elemento, por su id.
 */
id: string, 
/**
 * Dónde empieza su código, en bytes desde el principio.
 */
start: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
end: number, };
