// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Un mensaje de Typst sobre el documento.
 */
export type Diagnostic = { 
/**
 * Si es un error o un aviso.
 */
severity: Severity, 
/**
 * El mensaje, tal como lo da Typst.
 */
message: string, 
/**
 * Sugerencias de Typst para arreglarlo, si las hay.
 */
hints: Array<string>, 
/**
 * El elemento del documento en el que ocurre, si se puede saber.
 *
 * Se deduce de la línea del código generado en la que Typst sitúa el
 * problema: cada elemento ocupa una línea que acaba en su etiqueta
 * `<el-ID>`. Un problema que no cae en la línea de ningún elemento
 * —en la cabecera, o sin posición— no tiene elemento.
 */
element_id: string | null, };

/**
 * Gravedad de un diagnóstico de Typst.
 */
export type Severity = "error" | "warning";
