// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A qué se exporta.
 */
export type Format = { "format": "pdf" } | { "format": "svg" } | { "format": "png", 
/**
 * Puntos por pulgada: 72 es el tamaño natural, 300 es imprenta.
 */
ppi: number, } | { "format": "typ" };

/**
 * Qué páginas se exportan. Se cuentan desde 1, como se ven.
 */
export type Pages = { "pages": "all" } | { "pages": "only", 
/**
 * Cuál, contando desde 1.
 */
page: number, } | { "pages": "range", 
/**
 * La primera, contando desde 1.
 */
from: number, 
/**
 * La última, contando desde 1.
 */
to: number, };
