// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dónde quedó un elemento al componer el documento.
 */
export type LayoutBox = { 
/**
 * El id del elemento.
 */
id: string, 
/**
 * La página, contando desde 0.
 */
page: number, 
/**
 * Esquina superior izquierda de la caja **sin girar**, en mm.
 */
x: number, 
/**
 * Esquina superior izquierda de la caja sin girar, en mm.
 */
y: number, 
/**
 * Ancho sin girar, en mm.
 */
w: number, 
/**
 * Alto sin girar, en mm. En un texto con alto automático, el que midió
 * Typst.
 */
h: number, 
/**
 * Giro en grados, en sentido horario alrededor del centro de la caja,
 * entre -180 y 180. 0 si no está girado.
 */
rotation: number, 
/**
 * La caja que ocupa en la página tal como se dibuja, ya girada,
 * alineada con los bordes de la página. Sin giro, es la misma.
 */
bounds: MmRect, 
/**
 * Si lo que dibuja el elemento es una sola línea, sus dos extremos
 * **sin girar**, en mm. Su caja no dice en qué diagonal está: esto sí.
 */
line: MmSegment | null, };

/**
 * Un rectángulo en milímetros, con el origen arriba a la izquierda de la
 * página.
 */
export type MmRect = { 
/**
 * Distancia desde el borde izquierdo.
 */
x: number, 
/**
 * Distancia desde el borde superior.
 */
y: number, 
/**
 * Ancho.
 */
w: number, 
/**
 * Alto.
 */
h: number, };

/**
 * Un segmento, en milímetros, con el origen arriba a la izquierda de la
 * página.
 */
export type MmSegment = { 
/**
 * Primer extremo.
 */
x1: number, 
/**
 * Primer extremo.
 */
y1: number, 
/**
 * Segundo extremo.
 */
x2: number, 
/**
 * Segundo extremo.
 */
y2: number, };
