// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qué parte del texto de un flujo quedó en una zona.
 */
export type FlowRange = { 
/**
 * El id de la zona.
 */
zone: string, 
/**
 * La página donde quedó, contando desde 0.
 */
page: number, 
/**
 * El primer carácter del texto del flujo que se compuso aquí.
 */
from: number, 
/**
 * El primero que ya no. Si es igual que `from`, la zona quedó vacía.
 */
to: number, };

/**
 * Un glifo dibujado, con su sitio en la página y en el texto.
 */
export type Glyph = { 
/**
 * Dónde empieza, en bytes, el texto que compone este glifo dentro del
 * texto del elemento (los tramos, uno detrás de otro).
 */
text_index: number, 
/**
 * La línea en la que quedó, contando desde 0. Las decide Typst: un
 * salto del documento y uno repartido al ajustar el texto se numeran
 * igual.
 */
line: number, 
/**
 * Borde izquierdo de su avance, en mm desde el borde izquierdo de la
 * página.
 */
x: number, 
/**
 * Borde superior de su línea, en mm desde el borde superior de la
 * página.
 */
y: number, 
/**
 * Lo que avanza la escritura al dibujarlo, en mm. Con `x`, los dos
 * sitios donde puede ir el cursor.
 */
width: number, 
/**
 * Alto de la línea a la que pertenece, en mm: de la parte alta de la
 * fuente a la baja, con su tamaño. Es el alto del cursor.
 */
line_height: number, 
/**
 * La línea base sobre la que se apoya, en mm desde el borde superior de
 * la página.
 */
baseline: number, };

/**
 * Dónde quedó un elemento al componer el documento.
 */
export type LayoutBox = { 
/**
 * El id del elemento.
 */
id: string, 
/**
 * La página, contando desde 0.
 */
page: number, 
/**
 * Esquina superior izquierda de la caja **sin girar**, en mm.
 */
x: number, 
/**
 * Esquina superior izquierda de la caja sin girar, en mm.
 */
y: number, 
/**
 * Ancho sin girar, en mm.
 */
w: number, 
/**
 * Alto sin girar, en mm. En un texto con alto automático, el que midió
 * Typst.
 */
h: number, 
/**
 * Giro en grados, en sentido horario alrededor del centro de la caja,
 * entre -180 y 180. 0 si no está girado.
 */
rotation: number, 
/**
 * La caja que ocupa en la página tal como se dibuja, ya girada,
 * alineada con los bordes de la página. Sin giro, es la misma.
 */
bounds: MmRect, 
/**
 * Si lo que dibuja el elemento es una sola línea, sus dos extremos
 * **sin girar**, en mm. Su caja no dice en qué diagonal está: esto sí.
 */
line: MmSegment | null, 
/**
 * Cuánto se sale el contenido por debajo de la caja, en mm, o 0 si
 * cabe.
 *
 * Solo pasa con un alto fijo: con `h: null` la caja la mide Typst y
 * siempre cabe. Lo que sobra no se recorta, se dibuja fuera del marco
 * —también en el PDF—, así que hay que avisarlo (ver
 * [`overflowing`]).
 */
overflow: number, };

/**
 * Un rectángulo en milímetros, con el origen arriba a la izquierda de la
 * página.
 */
export type MmRect = { 
/**
 * Distancia desde el borde izquierdo.
 */
x: number, 
/**
 * Distancia desde el borde superior.
 */
y: number, 
/**
 * Ancho.
 */
w: number, 
/**
 * Alto.
 */
h: number, };

/**
 * Un segmento, en milímetros, con el origen arriba a la izquierda de la
 * página.
 */
export type MmSegment = { 
/**
 * Primer extremo.
 */
x1: number, 
/**
 * Primer extremo.
 */
y1: number, 
/**
 * Segundo extremo.
 */
x2: number, 
/**
 * Segundo extremo.
 */
y2: number, };
