// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alineación horizontal del texto.
 */
export type Align = "left" | "center" | "right" | "justify";

/**
 * Estilo de un trazo que no es continuo.
 */
export type Dash = "dashed" | "dotted" | "dash-dotted";

/**
 * Un documento completo de Galera.
 *
 * Es lo que se guarda como `document.json` dentro de un proyecto `.galera`.
 */
export type Document = { 
/**
 * Versión del formato. Solo se acepta [`DOCUMENT_VERSION`](crate::DOCUMENT_VERSION).
 *
 * Se valida al deserializar en vez de dejarlo para más tarde: un
 * documento de una versión futura se rechaza entero antes de que nadie
 * lo interprete a medias.
 */
version: number, 
/**
 * Metadatos del documento.
 */
meta: Meta, 
/**
 * Archivos de fuente que el proyecto empaqueta, relativos a su raíz.
 *
 * Las fuentes viajan con el documento (principio 4): nunca se usan las
 * que haya instaladas en la máquina.
 */
fonts: Array<string>, 
/**
 * Imágenes del proyecto, de clave a ruta relativa a la raíz.
 *
 * Los elementos [`Element::Image`] se refieren a la clave, no a la
 * ruta, para poder mover un archivo sin tocar cada elemento.
 */
assets: { [key in string]: string }, 
/**
 * Variables del documento, para plantillas y generación en lote.
 */
variables: { [key in string]: string }, 
/**
 * Páginas, en el orden en que se imprimen.
 */
pages: Array<Page>, };

/**
 * Un elemento colocado sobre una página.
 *
 * En el JSON, el campo `type` elige la variante y el resto de campos
 * aparecen todos al mismo nivel.
 */
export type Element = { "type": "text", 
/**
 * Contenido, partido en tramos con el mismo formato.
 */
content: Array<Run>, 
/**
 * Estilo que se aplica a todo el bloque.
 */
style: TextStyle, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "rect", 
/**
 * Color de relleno `#RRGGBB` o `#RRGGBBAA`, o `None` para no rellenar.
 */
fill: string | null, 
/**
 * Borde, o `None` para no dibujarlo.
 */
stroke: Stroke | null, 
/**
 * Radio de las esquinas, en milímetros.
 */
radius: number, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "ellipse", 
/**
 * Color de relleno, o `None` para no rellenar.
 */
fill: string | null, 
/**
 * Borde, o `None` para no dibujarlo.
 */
stroke: Stroke | null, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "line", 
/**
 * Identificador único dentro del documento.
 */
id: string, 
/**
 * Coordenada X del primer extremo, en milímetros.
 */
x: number, 
/**
 * Coordenada Y del primer extremo, en milímetros.
 */
y: number, 
/**
 * Coordenada X del segundo extremo, en milímetros.
 */
x2: number, 
/**
 * Coordenada Y del segundo extremo, en milímetros.
 */
y2: number, 
/**
 * Rotación en grados alrededor del punto medio.
 */
rotation: number, 
/**
 * Trazo con el que se dibuja.
 */
stroke: Stroke, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "image", 
/**
 * Clave dentro de [`Document::assets`].
 */
asset: string, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "code", 
/**
 * Código Typst, literal.
 */
source: string, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, };

/**
 * Datos comunes a casi todos los elementos: identidad, posición y tamaño.
 *
 * Se aplana dentro de cada variante de [`Element`], así que en el JSON
 * estos campos aparecen al mismo nivel que los propios del tipo.
 */
export type ElementBox = { 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, };

/**
 * Lo que el panel de capas guarda de cada elemento: un nombre propio, si
 * está oculto y si está bloqueado.
 *
 * Los tres son opcionales y, sin valor, **no se escriben** en el JSON: un
 * documento anterior a ellos se lee igual y, si no se tocan, se guarda
 * byte a byte igual.
 */
export type Layer = { 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, };

/**
 * Metadatos del documento.
 */
export type Meta = { 
/**
 * Título, que también da el nombre por defecto al exportar.
 */
title: string, };

/**
 * Una página del documento.
 */
export type Page = { 
/**
 * Identificador único dentro del documento.
 */
id: string, 
/**
 * Tamaño del papel.
 */
size: PageSize, 
/**
 * Elementos de la página, **en orden de capas**: el último del arreglo
 * es el que queda encima de todos.
 */
elements: Array<Element>, };

/**
 * Tamaño de una página.
 */
export type PageSize = { 
/**
 * Ancho, en [`PageSize::unit`].
 */
width: number, 
/**
 * Alto, en [`PageSize::unit`].
 */
height: number, 
/**
 * Unidad de las dos medidas.
 */
unit: Unit, };

/**
 * Un tramo de texto con el mismo formato.
 *
 * El contenido de un bloque de texto es una lista de tramos: "Informe" en
 * negrita seguido de " anual" en redonda son dos tramos.
 */
export type Run = { 
/**
 * El texto, en claro.
 *
 * Se guarda sin escapar. El escape hacia Typst ocurre al generar el
 * código, no al guardarlo (principio 6).
 */
text: string, 
/**
 * Negrita.
 */
bold: boolean, 
/**
 * Cursiva.
 */
italic: boolean, 
/**
 * Subrayado.
 */
underline: boolean, 
/**
 * Color del tramo, `#RRGGBB` o `#RRGGBBAA`. Sin él, el del bloque.
 */
color?: string | null, };

/**
 * Trazo de un borde o de una línea.
 */
export type Stroke = { 
/**
 * Color, `#RRGGBB` o `#RRGGBBAA`.
 */
color: string, 
/**
 * Grosor en milímetros.
 */
width: number, 
/**
 * Estilo del trazo, o `None` para continuo. Sin valor no se escribe en
 * el JSON: los documentos de antes se leen y se guardan igual.
 */
dash?: Dash, };

/**
 * Estilo de un bloque de texto completo.
 */
export type TextStyle = { 
/**
 * Familia tipográfica, entre las que el proyecto empaqueta.
 */
font: string, 
/**
 * Tamaño en puntos.
 */
size: number, 
/**
 * Color del texto, `#RRGGBB` o `#RRGGBBAA`.
 */
color: string, 
/**
 * Alineación horizontal.
 */
align: Align, 
/**
 * Interlineado, como múltiplo del tamaño de fuente.
 */
leading: number, 
/**
 * Espacio entre párrafos, como múltiplo del tamaño de fuente, o `None`
 * para el de Typst ([`DEFAULT_PARAGRAPH_SPACING`]). Sin valor no se
 * escribe en el JSON.
 */
spacing?: number, };

/**
 * Unidad de medida.
 */
export type Unit = "mm" | "cm" | "in" | "pt";
