// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alineación horizontal del texto.
 */
export type Align = "left" | "center" | "right" | "justify";

/**
 * Estilo de un trazo que no es continuo.
 */
export type Dash = "dashed" | "dotted" | "dash-dotted";

/**
 * Un documento completo de Galera.
 *
 * Es lo que se guarda como `document.json` dentro de un proyecto `.galera`.
 */
export type Document = { 
/**
 * Versión del formato. Solo se acepta [`DOCUMENT_VERSION`](crate::DOCUMENT_VERSION).
 *
 * Se valida al deserializar en vez de dejarlo para más tarde: un
 * documento de una versión futura se rechaza entero antes de que nadie
 * lo interprete a medias.
 */
version: number, 
/**
 * Metadatos del documento.
 */
meta: Meta, 
/**
 * Archivos de fuente que el proyecto empaqueta, relativos a su raíz.
 *
 * Las fuentes viajan con el documento (principio 4): nunca se usan las
 * que haya instaladas en la máquina.
 */
fonts: Array<string>, 
/**
 * Imágenes del proyecto, de clave a ruta relativa a la raíz.
 *
 * Los elementos [`Element::Image`] se refieren a la clave, no a la
 * ruta, para poder mover un archivo sin tocar cada elemento.
 */
assets: { [key in string]: string }, 
/**
 * Variables del documento, para plantillas y generación en lote.
 *
 * Se usan dentro de los textos y de los bloques de código escribiendo
 * `{{nombre}}` (ver [`crate::variables`]).
 */
variables: { [key in string]: Variable }, 
/**
 * Los textos que fluyen, de nombre a flujo.
 *
 * Cada uno lleva su contenido y la cadena de zonas por las que pasa
 * (ver [`flow`]). Las zonas son elementos [`Element::Flow`] de las
 * páginas, y pueden estar en páginas distintas.
 *
 * Un documento sin flujos no escribe el campo: los que ya existen
 * siguen guardándose igual que antes.
 */
flows?: { [key in string]: Flow }, 
/**
 * Páginas, en el orden en que se imprimen.
 */
pages: Array<Page>, };

/**
 * Un elemento colocado sobre una página.
 *
 * En el JSON, el campo `type` elige la variante y el resto de campos
 * aparecen todos al mismo nivel.
 */
export type Element = { "type": "text", 
/**
 * Contenido, partido en tramos con el mismo formato.
 */
content: Array<Run>, 
/**
 * Estilo que se aplica a todo el bloque.
 */
style: TextStyle, 
/**
 * Cómo se compone cada línea del bloque: si es un elemento de una
 * lista y con cuánto anidado. Las líneas son las que separan los
 * saltos de línea del contenido, contando desde 0; una línea sin
 * entrada aquí es texto normal, y la lista puede ser más corta que
 * el número de líneas.
 */
lines?: Array<Line>, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "rect", 
/**
 * Color de relleno `#RRGGBB` o `#RRGGBBAA`, o `None` para no rellenar.
 */
fill: string | null, 
/**
 * Borde, o `None` para no dibujarlo.
 */
stroke: Stroke | null, 
/**
 * Radio de las esquinas, en milímetros.
 */
radius: number, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "ellipse", 
/**
 * Color de relleno, o `None` para no rellenar.
 */
fill: string | null, 
/**
 * Borde, o `None` para no dibujarlo.
 */
stroke: Stroke | null, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "line", 
/**
 * Identificador único dentro del documento.
 */
id: string, 
/**
 * Coordenada X del primer extremo, en milímetros.
 */
x: number, 
/**
 * Coordenada Y del primer extremo, en milímetros.
 */
y: number, 
/**
 * Coordenada X del segundo extremo, en milímetros.
 */
x2: number, 
/**
 * Coordenada Y del segundo extremo, en milímetros.
 */
y2: number, 
/**
 * Rotación en grados alrededor del punto medio.
 */
rotation: number, 
/**
 * Trazo con el que se dibuja.
 */
stroke: Stroke, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "image", 
/**
 * Clave dentro de [`Document::assets`].
 */
asset: string, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "code", 
/**
 * Código Typst, literal.
 */
source: string, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "flow", 
/**
 * A qué flujo pertenece: una clave de [`Document::flows`].
 */
flow: string, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, } | { "type": "group", 
/**
 * Lo que lleva dentro, **en orden de capas** y en coordenadas
 * relativas a la esquina del grupo.
 */
children: Array<Element>, 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, };

/**
 * Datos comunes a casi todos los elementos: identidad, posición y tamaño.
 *
 * Se aplana dentro de cada variante de [`Element`], así que en el JSON
 * estos campos aparecen al mismo nivel que los propios del tipo.
 */
export type ElementBox = { 
/**
 * Identificador único dentro del documento.
 *
 * Es también la etiqueta `<el-ID>` que el codegen deja en el código
 * Typst para poder encontrar el elemento en el layout compilado.
 */
id: string, 
/**
 * Distancia desde el borde izquierdo de la página, en milímetros.
 */
x: number, 
/**
 * Distancia desde el borde superior de la página, en milímetros.
 */
y: number, 
/**
 * Ancho, en milímetros.
 */
w: number, 
/**
 * Alto en milímetros, o `None` para que lo mida Typst.
 *
 * La altura automática es lo normal en textos e imágenes: lo que ocupan
 * depende de la composición, y solo Typst la conoce (principio 3).
 */
h: number | null, 
/**
 * Rotación en grados, en sentido horario, alrededor del centro.
 */
rotation: number, 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, };

/**
 * Un texto que fluye por una cadena de zonas.
 */
export type Flow = { 
/**
 * El texto entero, partido en tramos con el mismo formato.
 *
 * Es de todo el flujo, no de una zona: dónde se corta lo decide la
 * composición.
 */
content: Array<Run>, 
/**
 * Estilo que se aplica a todo el flujo.
 *
 * Va aquí y no en cada zona por lo mismo que el contenido: es un texto
 * solo, y no cambiaría de fuente al pasar de página.
 */
style: TextStyle, 
/**
 * Las zonas por las que pasa, **en orden**.
 */
zones: Array<string>, };

/**
 * Lo que el panel de capas guarda de cada elemento: un nombre propio, si
 * está oculto y si está bloqueado.
 *
 * Los tres son opcionales y, sin valor, **no se escriben** en el JSON: un
 * documento anterior a ellos se lee igual y, si no se tocan, se guarda
 * byte a byte igual.
 */
export type Layer = { 
/**
 * Nombre que se enseña en el panel en vez del que se deduce del
 * elemento.
 */
name?: string, 
/**
 * Si está oculto: no se emite en el código Typst, así que ni se dibuja
 * ni se exporta.
 */
hidden?: boolean, 
/**
 * Si está bloqueado: no se puede seleccionar en el lienzo, solo desde
 * el panel de capas.
 */
locked?: boolean, };

/**
 * Cómo se compone una línea de un bloque de texto.
 *
 * El contenido de un bloque es texto con saltos de línea; lo que hace de
 * una línea un elemento de lista no está en el texto, sino aquí: así el
 * texto se sigue leyendo tal cual y el guion de una viñeta no se confunde
 * con un guion escrito.
 */
export type Line = { 
/**
 * La lista de la que es elemento, si lo es.
 */
list?: ListKind | null, 
/**
 * Cuánto se anida dentro de la lista, desde 0. Sin lista no significa
 * nada.
 */
level?: number, };

/**
 * Qué clase de lista.
 */
export type ListKind = "bullet" | "numbered";

/**
 * Metadatos del documento.
 */
export type Meta = { 
/**
 * Título, que también da el nombre por defecto al exportar.
 */
title: string, };

/**
 * Una página del documento.
 */
export type Page = { 
/**
 * Identificador único dentro del documento.
 */
id: string, 
/**
 * Tamaño del papel.
 */
size: PageSize, 
/**
 * Elementos de la página, **en orden de capas**: el último del arreglo
 * es el que queda encima de todos.
 */
elements: Array<Element>, };

/**
 * Tamaño de una página.
 */
export type PageSize = { 
/**
 * Ancho, en [`PageSize::unit`].
 */
width: number, 
/**
 * Alto, en [`PageSize::unit`].
 */
height: number, 
/**
 * Unidad de las dos medidas.
 */
unit: Unit, };

/**
 * Un tramo de texto con el mismo formato.
 *
 * El contenido de un bloque de texto es una lista de tramos: "Informe" en
 * negrita seguido de " anual" en redonda son dos tramos.
 */
export type Run = { 
/**
 * El texto, en claro.
 *
 * Se guarda sin escapar. El escape hacia Typst ocurre al generar el
 * código, no al guardarlo (principio 6).
 */
text: string, 
/**
 * Negrita.
 */
bold: boolean, 
/**
 * Cursiva.
 */
italic: boolean, 
/**
 * Subrayado.
 */
underline: boolean, 
/**
 * Color del tramo, `#RRGGBB` o `#RRGGBBAA`. Sin él, el del bloque.
 */
color?: string | null, 
/**
 * A dónde lleva el tramo, si es un enlace. Solo `http://`, `https://`
 * y `mailto:` (ver [`is_valid_link`](crate::model::is_valid_link)).
 */
link?: string | null, };

/**
 * Trazo de un borde o de una línea.
 */
export type Stroke = { 
/**
 * Color, `#RRGGBB` o `#RRGGBBAA`.
 */
color: string, 
/**
 * Grosor en milímetros.
 */
width: number, 
/**
 * Estilo del trazo, o `None` para continuo. Sin valor no se escribe en
 * el JSON: los documentos de antes se leen y se guardan igual.
 */
dash?: Dash, };

/**
 * Estilo de un bloque de texto completo.
 */
export type TextStyle = { 
/**
 * Familia tipográfica, entre las que el proyecto empaqueta.
 */
font: string, 
/**
 * Tamaño en puntos.
 */
size: number, 
/**
 * Color del texto, `#RRGGBB` o `#RRGGBBAA`.
 */
color: string, 
/**
 * Alineación horizontal.
 */
align: Align, 
/**
 * Interlineado, como múltiplo del tamaño de fuente.
 */
leading: number, 
/**
 * Espacio entre párrafos, como múltiplo del tamaño de fuente, o `None`
 * para el de Typst ([`DEFAULT_PARAGRAPH_SPACING`]). Sin valor no se
 * escribe en el JSON.
 */
spacing?: number, };

/**
 * Unidad de medida.
 */
export type Unit = "mm" | "cm" | "in" | "pt";

/**
 * Una variable del documento: de qué es y qué vale.
 *
 * Se escribe como `{ "kind": "date", "value": "2026-09-21" }`, y se **lee**
 * también como el valor a secas —`"nombre": "Cooperativa"`—, que es como
 * se escribían antes de tener tipo: los documentos que ya existían siguen
 * abriéndose, y al guardarlos quedan con su tipo escrito.
 */
export type Variable = { 
/**
 * De qué es: texto, número, fecha o imagen.
 */
kind: VariableKind, 
/**
 * Su valor, tal cual se escribió.
 */
value: string, };

/**
 * De qué es una variable.
 *
 * El tipo no cambia cómo se sustituye —siempre es texto lo que entra en el
 * documento—, pero sí **qué valores se admiten**: una fecha que no existe o
 * una imagen que no está son problemas del documento, y se dicen al
 * validarlo.
 */
export type VariableKind = "text" | "number" | "date" | "image";
