// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MmRect } from "./layout";
import type { Element, Flow, Line, Page, Run, Stroke, TextStyle, Variable } from "./model";

/**
 * Qué formato se cambia en un tramo. Lo que va a `None` se queda como
 * estaba: poner en negrita una selección no toca su cursiva.
 */
export type Format = { 
/**
 * Negrita.
 */
bold?: boolean | null, 
/**
 * Cursiva.
 */
italic?: boolean | null, 
/**
 * Subrayado.
 */
underline?: boolean | null, 
/**
 * Color del tramo. Ponerlo a nulo lo quita, y el texto vuelve al
 * color del bloque.
 */
color?: string | null | null, 
/**
 * A dónde lleva el tramo. Ponerlo a nulo quita el enlace.
 */
link?: string | null | null, };

/**
 * Un cambio del documento.
 */
export type Op = { "op": "move", 
/**
 * El elemento.
 */
id: string, 
/**
 * Hacia la derecha, en mm.
 */
dx: number, 
/**
 * Hacia abajo, en mm.
 */
dy: number, } | { "op": "resize", 
/**
 * El elemento.
 */
id: string, 
/**
 * Nueva esquina superior izquierda, en mm.
 */
x: number, 
/**
 * Nueva esquina superior izquierda, en mm.
 */
y: number, 
/**
 * Nuevo ancho, en mm.
 */
w: number, 
/**
 * Nuevo alto, en mm, o `null` para el automático.
 */
h: number | null, } | { "op": "rotate", 
/**
 * El elemento.
 */
id: string, 
/**
 * El giro nuevo.
 */
rotation: number, } | { "op": "insert_text", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde se mete, en caracteres desde el principio del texto.
 */
at: number, 
/**
 * Lo que se escribe.
 */
text: string, } | { "op": "delete_text", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde empieza, en caracteres.
 */
from: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
to: number, } | { "op": "set_lines", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde empieza, en caracteres.
 */
from: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
to: number, 
/**
 * Cómo quedan esas líneas.
 */
line: Line, } | { "op": "format_text", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde empieza, en caracteres.
 */
from: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
to: number, 
/**
 * Qué se cambia. Lo que no se diga se queda como estaba.
 */
format: Format, } | { "op": "set_property", 
/**
 * El elemento.
 */
id: string, 
/**
 * La propiedad y su valor nuevo.
 */
property: Property, } | { "op": "create", 
/**
 * La página, por su id.
 */
page: string, 
/**
 * Dónde en el orden de capas: 0 es el de más abajo.
 */
index: number | null, 
/**
 * El elemento, con un id que no use nadie.
 */
element: Element, } | { "op": "delete", 
/**
 * El elemento.
 */
id: string, } | { "op": "rename", 
/**
 * El elemento.
 */
id: string, 
/**
 * Su id nuevo.
 */
to: string, } | { "op": "reorder", 
/**
 * El elemento.
 */
id: string, 
/**
 * La posición nueva: 0 es la de más abajo.
 */
index: number, } | { "op": "restore", 
/**
 * El elemento tal como tiene que quedar.
 */
element: Element, } | { "op": "add_asset", 
/**
 * La clave nueva.
 */
key: string, 
/**
 * La ruta del archivo, relativa a la raíz del proyecto.
 */
path: string, } | { "op": "remove_asset", 
/**
 * La clave.
 */
key: string, } | { "op": "set_variable", 
/**
 * Su nombre.
 */
name: string, 
/**
 * Lo que pasa a ser: su tipo y su valor.
 */
variable: Variable, } | { "op": "remove_variable", 
/**
 * Su nombre.
 */
name: string, } | { "op": "rename_variable", 
/**
 * El nombre de ahora.
 */
from: string, 
/**
 * El nombre nuevo.
 */
to: string, } | { "op": "set_title", 
/**
 * El título nuevo, sin espacios sobrantes a los lados.
 */
title: string, } | { "op": "add_font", 
/**
 * La ruta del archivo, relativa a la raíz del proyecto.
 */
path: string, 
/**
 * Dónde en la lista; sin él, al final.
 */
index: number | null, } | { "op": "remove_font", 
/**
 * La ruta tal como está en `fonts`.
 */
path: string, } | { "op": "rename_asset", 
/**
 * La clave de ahora.
 */
from: string, 
/**
 * La clave nueva.
 */
to: string, } | { "op": "insert_page", 
/**
 * Dónde va, contando desde 0; sin él, al final.
 */
index: number | null, 
/**
 * La página entera.
 */
page: Page, } | { "op": "remove_page", 
/**
 * La página, por su id.
 */
id: string, } | { "op": "duplicate_page", 
/**
 * La página que se copia.
 */
id: string, 
/**
 * El id de la copia, que no puede tenerlo nadie más.
 */
to: string, } | { "op": "reorder_page", 
/**
 * La página, por su id.
 */
id: string, 
/**
 * La posición nueva, contando desde 0.
 */
index: number, } | { "op": "group", 
/**
 * Los elementos, por su id.
 */
ids: Array<string>, 
/**
 * El id del grupo nuevo, que no puede tenerlo nadie más.
 */
id: string, 
/**
 * La caja del grupo, en mm.
 */
rect: MmRect, } | { "op": "ungroup", 
/**
 * El grupo, por su id.
 */
id: string, } | { "op": "create_flow", 
/**
 * Cómo se llama.
 */
name: string, 
/**
 * El flujo: su texto, su estilo y su cadena.
 */
flow: Flow, } | { "op": "remove_flow", 
/**
 * Cuál.
 */
name: string, } | { "op": "link_zone", 
/**
 * El flujo.
 */
flow: string, 
/**
 * La zona.
 */
zone: string, 
/**
 * En qué posición de la cadena, o al final si no se dice.
 */
index: number | null, } | { "op": "insert_flow_text", 
/**
 * El flujo.
 */
flow: string, 
/**
 * Dónde, en bytes del texto del flujo.
 */
at: number, 
/**
 * Lo que se mete.
 */
text: string, } | { "op": "delete_flow_text", 
/**
 * El flujo.
 */
flow: string, 
/**
 * Desde dónde, en bytes.
 */
from: number, 
/**
 * Hasta dónde, en bytes, sin incluirlo.
 */
to: number, } | { "op": "format_flow_text", 
/**
 * El flujo.
 */
flow: string, 
/**
 * Desde dónde, en bytes.
 */
from: number, 
/**
 * Hasta dónde, en bytes, sin incluirlo.
 */
to: number, 
/**
 * Qué se cambia.
 */
format: Format, } | { "op": "restore_flow", 
/**
 * Cuál.
 */
name: string, 
/**
 * Cómo estaba.
 */
flow: Flow, } | { "op": "unlink_zone", 
/**
 * La zona.
 */
zone: string, 
/**
 * Cómo se llama el flujo nuevo, que se crea aquí.
 */
to: string, } | { "op": "batch", 
/**
 * Los comandos, en el orden en que se aplican.
 */
ops: Array<Op>, };

/**
 * Una propiedad que se puede cambiar con [`Op::SetProperty`], con su valor.
 */
export type Property = { "name": "fill", "value": string | null } | { "name": "stroke", "value": Stroke | null } | { "name": "radius", "value": number } | { "name": "content", "value": Array<Run> } | { "name": "style", "value": TextStyle } | { "name": "source", "value": string } | { "name": "asset", "value": string } | { "name": "name", "value": string | null } | { "name": "hidden", "value": boolean } | { "name": "locked", "value": boolean };
