// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element, Line, Run, Stroke, TextStyle } from "./model";

/**
 * Qué formato se cambia en un tramo. Lo que va a `None` se queda como
 * estaba: poner en negrita una selección no toca su cursiva.
 */
export type Format = { 
/**
 * Negrita.
 */
bold?: boolean | null, 
/**
 * Cursiva.
 */
italic?: boolean | null, 
/**
 * Subrayado.
 */
underline?: boolean | null, 
/**
 * Color del tramo. Ponerlo a nulo lo quita, y el texto vuelve al
 * color del bloque.
 */
color?: string | null | null, 
/**
 * A dónde lleva el tramo. Ponerlo a nulo quita el enlace.
 */
link?: string | null | null, };

/**
 * Un cambio del documento.
 */
export type Op = { "op": "move", 
/**
 * El elemento.
 */
id: string, 
/**
 * Hacia la derecha, en mm.
 */
dx: number, 
/**
 * Hacia abajo, en mm.
 */
dy: number, } | { "op": "resize", 
/**
 * El elemento.
 */
id: string, 
/**
 * Nueva esquina superior izquierda, en mm.
 */
x: number, 
/**
 * Nueva esquina superior izquierda, en mm.
 */
y: number, 
/**
 * Nuevo ancho, en mm.
 */
w: number, 
/**
 * Nuevo alto, en mm, o `null` para el automático.
 */
h: number | null, } | { "op": "rotate", 
/**
 * El elemento.
 */
id: string, 
/**
 * El giro nuevo.
 */
rotation: number, } | { "op": "insert_text", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde se mete, en caracteres desde el principio del texto.
 */
at: number, 
/**
 * Lo que se escribe.
 */
text: string, } | { "op": "delete_text", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde empieza, en caracteres.
 */
from: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
to: number, } | { "op": "set_lines", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde empieza, en caracteres.
 */
from: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
to: number, 
/**
 * Cómo quedan esas líneas.
 */
line: Line, } | { "op": "format_text", 
/**
 * El elemento.
 */
id: string, 
/**
 * Dónde empieza, en caracteres.
 */
from: number, 
/**
 * Dónde acaba, sin incluirlo.
 */
to: number, 
/**
 * Qué se cambia. Lo que no se diga se queda como estaba.
 */
format: Format, } | { "op": "set_property", 
/**
 * El elemento.
 */
id: string, 
/**
 * La propiedad y su valor nuevo.
 */
property: Property, } | { "op": "create", 
/**
 * La página, por su id.
 */
page: string, 
/**
 * Dónde en el orden de capas: 0 es el de más abajo.
 */
index: number | null, 
/**
 * El elemento, con un id que no use nadie.
 */
element: Element, } | { "op": "delete", 
/**
 * El elemento.
 */
id: string, } | { "op": "rename", 
/**
 * El elemento.
 */
id: string, 
/**
 * Su id nuevo.
 */
to: string, } | { "op": "reorder", 
/**
 * El elemento.
 */
id: string, 
/**
 * La posición nueva: 0 es la de más abajo.
 */
index: number, } | { "op": "restore", 
/**
 * El elemento tal como tiene que quedar.
 */
element: Element, } | { "op": "add_asset", 
/**
 * La clave nueva.
 */
key: string, 
/**
 * La ruta del archivo, relativa a la raíz del proyecto.
 */
path: string, } | { "op": "remove_asset", 
/**
 * La clave.
 */
key: string, } | { "op": "set_variable", 
/**
 * Su nombre.
 */
name: string, 
/**
 * Su valor nuevo.
 */
value: string, } | { "op": "remove_variable", 
/**
 * Su nombre.
 */
name: string, } | { "op": "rename_variable", 
/**
 * El nombre de ahora.
 */
from: string, 
/**
 * El nombre nuevo.
 */
to: string, } | { "op": "set_title", 
/**
 * El título nuevo, sin espacios sobrantes a los lados.
 */
title: string, } | { "op": "add_font", 
/**
 * La ruta del archivo, relativa a la raíz del proyecto.
 */
path: string, 
/**
 * Dónde en la lista; sin él, al final.
 */
index: number | null, } | { "op": "remove_font", 
/**
 * La ruta tal como está en `fonts`.
 */
path: string, } | { "op": "rename_asset", 
/**
 * La clave de ahora.
 */
from: string, 
/**
 * La clave nueva.
 */
to: string, };

/**
 * Una propiedad que se puede cambiar con [`Op::SetProperty`], con su valor.
 */
export type Property = { "name": "fill", "value": string | null } | { "name": "stroke", "value": Stroke | null } | { "name": "radius", "value": number } | { "name": "content", "value": Array<Run> } | { "name": "style", "value": TextStyle } | { "name": "source", "value": string } | { "name": "asset", "value": string } | { "name": "name", "value": string | null } | { "name": "hidden", "value": boolean } | { "name": "locked", "value": boolean };
