// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MmRect, MmSegment } from "./layout";

/**
 * Qué parte del elemento se está moviendo en un eje.
 */
export type Grip = "whole" | "start" | "end" | "none";

/**
 * Qué se agarra en cada eje.
 */
export type Grips = { 
/**
 * En el eje horizontal.
 */
x: Grip, 
/**
 * En el eje vertical.
 */
y: Grip, };

/**
 * Una línea que hay que dibujar mientras se mueve el elemento.
 */
export type Guide = { 
/**
 * Los dos extremos del segmento, en mm de la página.
 *
 * Una guía de alineación va de punta a punta de lo que alinea; una de
 * espaciado recorre el hueco que mide.
 */
line: MmSegment, 
/**
 * De dónde sale.
 */
kind: GuideKind, };

/**
 * De dónde sale una guía.
 */
export type GuideKind = "element" | "page" | "margin" | "spacing";

/**
 * Cómo se ajusta este lienzo.
 */
export type Settings = { 
/**
 * A cuántos píxeles de pantalla engancha.
 */
threshold: number, 
/**
 * Cuántos píxeles de pantalla mide un milímetro: el zoom del lienzo.
 */
scale: number, 
/**
 * El margen al que ajustarse, en mm desde cada borde de la página, o
 * `None` si el lienzo no enseña márgenes.
 */
margin: number | null, };

/**
 * Dónde queda el elemento al soltarlo y qué guías enseñar.
 */
export type Snapped = { 
/**
 * Cuánto hay que correr lo que se agarra hacia la derecha, en mm. 0 si
 * no engancha.
 */
dx: number, 
/**
 * Cuánto hay que correrlo hacia abajo, en mm. 0 si no engancha.
 */
dy: number, 
/**
 * La caja ya ajustada. Al arrastrar es la de antes corrida `dx` y
 * `dy`; al redimensionar, la que deja el borde enganchado en su sitio.
 */
rect: MmRect, 
/**
 * Las guías que justifican ese desplazamiento.
 */
guides: Array<Guide>, };
