// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lo que se sabe de una plantilla sin abrirla.
 */
export type TemplateMeta = { 
/**
 * Cómo se llama, para la galería: «Factura».
 */
name: string, 
/**
 * Una línea de qué es y para qué sirve.
 */
description: string, 
/**
 * De qué grupo es, para ordenarlas: «negocio», «personal».
 */
category?: string | null, };
