/**
 * Los tipos del modelo se generan desde Rust (ver `src/types/` y
 * CONTRIBUTING.md). Estas pruebas vigilan que nadie los defina a mano.
 */
import { describe, expect, it } from "vitest";

const generated = import.meta.glob<string>("./types/*.ts", {
  query: "?raw",
  import: "default",
  eager: true,
});

const handWritten = import.meta.glob<string>(["./**/*.{ts,tsx}", "!./types/**"], {
  query: "?raw",
  import: "default",
  eager: true,
});

/** Los nombres de los tipos que declara un archivo. */
function declaredTypes(source: string): string[] {
  return [...source.matchAll(/^\s*(?:export\s+)?(?:type|interface)\s+(\w+)/gm)].map(
    (match) => match[1] ?? "",
  );
}

const generatedNames = Object.values(generated).flatMap(declaredTypes);

describe("tipos generados", () => {
  it("existen y traen el modelo y los diagnósticos", () => {
    expect(generatedNames).toEqual(
      expect.arrayContaining(["Document", "Page", "Element", "Run", "Diagnostic", "Severity"]),
    );
  });

  it("todos los archivos de src/types salen de ts-rs", () => {
    for (const [path, source] of Object.entries(generated)) {
      expect(source.startsWith("// This file was generated by [ts-rs]"), path).toBe(true);
    }
  });

  it("ningún archivo escrito a mano vuelve a declarar un tipo generado", () => {
    for (const [path, source] of Object.entries(handWritten)) {
      const repeated = declaredTypes(source).filter((name) => generatedNames.includes(name));
      expect(repeated, path).toEqual([]);
    }
  });
});
